### ISSUE TITLE
Integrating Complete Lodash Functionality

### ISSUE THREAD

**Issue by stramel** [richtmat/lodash-snippets#2]
- [x] Arrays
- [ ] Chaining
- [x] Collections
- [x] Functions _\- Merged with #3_
- [x] Objects _\- Merged with #4_
- [x] Utilities _\- Merged with #1_
